sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 2861587619
#注意：这里在git时不能携带oss密钥，需要进行一定配置
  alioss:
      access-key-id:  ${ALIOSS_ACCESS_KEY_ID}
      access-key-secret: ${ALIOSS_ACCESS_KEY_SECRET}
      bucket-name: ${ALIOSS_BUCKET_NAME}
      endpoint: ${ALIOSS_ENDPOINT}
  redis:
    host: localhost
    port: 6379
    password: 2861587619
    database: 0
  wechat:
    appid: wx08407ff2f1baa7db
    secret: 562f2c9164a62b1dcb8dfe5c51f17cc3